### ISSUE TITLE
Nothing happens after choosing target container

### ISSUE THREAD

**Issue by Congpy** [NydusOne/gcode-composer#15]
Hi, in the G-Code Composer window, I click "Choose target container". After the browser window pops up, I select an .obj file that is published under OSF Registry, however, nothing happens. Although I have tried both in Ubuntu and Windows I can't make it work.

**Comment by termi-official** [comment]
Hi @Congpy . Thanks for reporting the issue. One of the electron updates broke several things in the composer. Seems like I missed this bug in the latest patches. I may need a day or two to fix this.

**Comment by termi-official** [comment]
Can you take a look at the referenced PR if this one works for you?

**Comment by Congpy** [comment]
Works a like charm now!  Thank you!
